BetterTyped/react-zoom-pan-pinch

- src/components/TransformComponent.js
This removes double quotes from the class name react-transform-component in the TransformComponent component.
Closes #28
> Feature: Remove double quotes from react-transform-component

- src/components/TransformComponent.tsx
Hey,
I have noticed the zoom options are not working in chrome30 browser because transform is not supported in older browser.
so i have added webkitTransform css property for older browser kindly review it and merge it asap.
thanks for the awesome plugin
> fixed zoom issue on older browsers

- src/store/StateContext.tsx
Add to checkIsPanningActive to allow for a touch pan in only the Y direction. Currently, touch pans will be cancelled unless they have at least moved 1 pixel in the x direction
> Fix touch Y panning only

- src/components/transform-context.tsx
Hi,
Panning was using activationKeys property from wheel instead of panning which makes it unable to assign different activation keys for wheel and panning.
> fix activationKeys options in onPanning i onPanningStart

- package.json
Hi, thanks for the great library!
This issue was found by eslint in an application. The application compiled fine, but eslint errored with
```
1:54  error  Unable to resolve path to module 'react-zoom-pan-pinch'  import/no-unresolved
```
This was due to eslint trying to resolve the `jsnext:main` value in `package.json`, which this PR fixes.
> Fix filename for jsnext:main in package.json

- tsconfig.json
This resolves the issue with `Module not found: Can't resolve 'react/jsx-runtime' in '/node_modules/react-zoom-pan-pinch/dist'`
The "react-jsx" option inserts `import { jsx } from 'react/jsx-runtime';` into dist/index.esm.js which causes the import error.
Using the "react" option uses React.createElement instead, which already exists.
Fixes #218
> Switch from react-jsx to react to avoid import errors

- src/components/transform-component.module.css
- Small bugfix resolving the TransformComponent rendering on the LHS of the TransformWrapper when the centerOnInit prop is true (Vertical centering is working as expected).
- I may be mistaken but webpack and/or storybook is generating these styles automatically but rollup isn't hence why the issue doesn't show up in storybook.
- Note: If you are experiencing this issue and need an immediate fix add `width & height: -moz-fit-content;` to a style/class passed to TransformWrapper and TransformComponent.
> Include -moz-fit-content in wrapper and content classes

- src/core/pan/panning.utils.ts
If the object moved along one axis without moving along the other axis, the object moved jerkily
> Fixed slowing down when moving

- package.json
This adds "src" to the set of published files, which allows source mapped URLs to resolve for consumers of this package. Resolves #265.
If the download size of the package is what we want to optimize for, an alternative approach would be to remove source map URL comments from the production build of this package.
> Publish src folder

- src/components/transform-context.tsx
Otherwise this lingering event listener causes memory leak.
Resolves #269.
> Clean up event listener upon transform-context unmount

- src/utils/styles.utils.ts
On Safari ( both Desktop and iOS ) there is a [bug with Webkit](https://bugs.webkit.org/show_bug.cgi?id=27684) around scaling images / SVGs that makes them pixelated. By using `transform: matrix()` instead of `transform: translate3d() scale()` this removes the issue and is compatible with that was being archived with the scale and translate.
> Add fix for scaling issue with SVG's on Safari

- src/stories/examples/content-rerendering/example.tsx
Hello 👋 
As part of our project, we are using Facebook's new Memlab tool to detect memory leaks in SPA applications. 
While running the tool and analyzing the code of react-zoom-pan-pinch, we saw that your project does a very good job of ensuring that all async operations are cancelled when the component unmounts. However, as per Memlab execution results, we found some dangling intervals that were causing the memory to leak (screenshots below).
[before]
<br />
Hence we added the fix by clearing the intervals and you can see the # of leaks reducing noticeably:
<br />
You can analyze this and other potential leak sources, if you like, by running [Memlab](https://facebook.github.io/memlab/) with a scenario file covering maximum # of use cases.
Following is a sample of the scenario file we …
> Clear intervals to avoid detached components and memory leaks

- src/utils/styles.utils.ts
Originally opened here https://github.com/proNestorAps/react-zoom-pan-pinch/pull/90 but it is archived.
Refer to https://github.com/hueyyeng/simple-react-lightbox/issues/6 for more details
Previously a forked library I'm using uses https://github.com/prc5/react-zoom-pan-pinch and I saw this forked repo contains new fixes and actively maintained. So I opted to point the dependencies to this one and all is good except when I noticed the panning and zooming performance is choppy on iPad Pro.
Since the original implementation uses translate3d() and that has their own Safari issues, I saw you change it to use matrix() (_this refer to one of the pull request that has been merged here_) that fixes those issues but it resulted in the choppy performance I'm encountering on iPad Pro. Strangely the …
> Use matrix3d() for transform

- src/core/animations/animations.utils.ts
- src/core/double-click/double-click.logic.ts
- src/core/handlers/handlers.utils.ts
- src/core/instance.core.ts
Trigger **onZoomStart**, **onZoom** and **onZoomStop** while double clicking for **zoomIn**/**zoomOut**/**reset** mode. https://github.com/prc5/react-zoom-pan-pinch/issues/305
> Add onZoom callbacks to a double click

- README.md
<> and <React.Fragment> were used inconsistently, the component started with <> but was closed with </React.Fragment> i have replaced <> by  <React.Fragment> which is also consistent with other examples.
> Update README.md to fix error in code snippet

- package.json
- rollup.config.js
- yarn.lock
I found an issue like this thread. https://github.com/prc5/react-zoom-pan-pinch/issues/356
**What is included in this PR?**
- Package updated for fixing peer dependency conflict. I found this when I debug this package by running `npm pack`.
- Disable source map handler from TypeScript plugin and let Rollup managed it. Ref: https://stackoverflow.com/a/63235210
**How to test?**
- Check out this branch.
- Run `yarn & yarn build`.
- Run `npm pack`. You will get a file at the root of the project called `react-zoom-pan-pinch-0.0.0.tgz`.
- Go to the target project that uses this library and edit `package.json` to add `"react-zoom-pan-pinch": "file:../react-zoom-pan-pinch/react-zoom-pan-pinch-0.0.0.tgz",` as dependency. 
- Test it whatever.
**Proof.**
I can debug on typescript code like this. We …
> Fix source map not found on source-map-loader

- src/core/handlers/handlers.utils.ts
- src/core/wheel/wheel.utils.ts
#275 Points out an issue where the scale calculation is inaccurate based on the provided step sensitivity.
For instance, if the current scale is 1, and the step sensitivity is 0.5, zooming will result in the scale going from 1 -> 1.65 -> 2.72.
With the proposed change, zooming will produce a scale going from 1 -> 1.5 -> 2.
> Fix scale calculation

- tsconfig.json
TS 5.5 will depreceate "suppressImplicitAnyIndexErrors", which means errors are being thrown in projects using more up-to-date TS versions. This fix simply ingores 5.0 deprecation errors as the TS docs suggest.
> fix: 🐛 ignore TS 5.0 deprecations

- src/stories/docs/props.tsx
Fixes #365: `zoomAnimation.size` default value was previously a boolean instead of a number:
Changed to use correct value `state.constants.ts`:
---
Also fixes `panning.lockAxisX` and `panning.lockAxisY`, which were previously a copy paste error from `panning.activationKeys`:
Changed to use correct values from `state.constants.ts`, and updated description:
> docs: ✏️ Fix storybook props

- src/core/pan/panning.utils.ts
Related issue: #371 
This fixes an issue where mouse event panning wasn't functional when the component was used within shadow DOM.
This is due to [event retargeting](https://polymer-library.polymer-project.org/2.0/docs/devguide/shadow-dom#event-retargeting). When the `mousemove`/etc events bubble up from within the shadow DOM, the event target gets set to the shadow DOM's host element. This breaks an assumption in the panning event handler that `event.target` will be a descendent of the `wrapperComponent`, so when the library calls `wrapperComponent.contains(event.target)`, the result is always `false`.
This PR addresses the issue by checking if the event target is a shadow DOM host. If it is, we check if `wrapperComponent` contains any elements returned by `event.composedPath()`, …
> fix: Mouse panning when used in shadow DOM

- src/core/double-click/double-click.logic.ts
- src/models/context.model.ts
- src/stories/docs/props.tsx
- src/typings.d.ts
Fixes https://github.com/prc5/react-zoom-pan-pinch/issues/409
Note: `yarn format` also formats some other files, so I excluded those. A project maintainer should likely run `yarn format` on the `master` branch, or I can run it to be included in this PR on request.
> Add toggle double-click mode

- src/core/instance.core.ts
Hi, when the callbacks in react are updated, the instance on update was not picking up the new props and the instance was accessing the old cached value.
> bugfix(TransformWrapper): update props when TransformWrapper is updated

- src/utils/helpers.utils.ts
This PR addresses #407 by determining whether a node is directly excluded or is a descendant of an excluded node using a simple constructed CSS selector that the node is matched against.
In our project we use this component to zoom/pan a large and complex DOM that has deep nested elements, so it is quite cumbersome and intrusive to add classnames to all descendants of an excluded element.
While this simple change only addresses the issue raised, ideally though the exclusion rules should be changed to be proper selectors rather than just class or tag names, that would allow unlimited flexibility, however that would also be a breaking change.
> Exclude all nested elements

- src/components/mini-map/use-resize.hook.ts
This PR introduces a check for the availability of `ResizeObserver` in the `window` object within our custom `useResize` hook. This change aims to prevent errors in environments where `ResizeObserver` is not defined, such as server-side rendering contexts or older browsers, and during Jest testing without specific mocks.
While implementing the `useResize` hook for element resize observation, we encountered errors in environments lacking `ResizeObserver` support. Specifically, Jest tests failed with a `ReferenceError: ResizeObserver is not defined`, unless a mock implementation was provided:
```javascript
window.ResizeObserver = jest.fn().mockImplementation(() => ({
disconnect: jest.fn(),
observe: jest.fn(),
}));
```
- https://github.com/jaredLunde/react-hook/blob/master/packages/resize-obs …
> feat: Add check for ResizeObserver availability to prevent reference errors

- src/core/instance.core.ts
This addresses this issue: https://github.com/BetterTyped/react-zoom-pan-pinch/issues/392
It seems like, maybe depending on what html and CSS you are using in the code surrounding your image, the `contentComponent` will trigger the `ResizeObserver` multiple times before the image is actually loaded. Given that the `ResizeObserver` is coded to only run once, this leaves the image off-center in some cases.
I've set it up so that the `ResizeObserver` will wait until the `contentComponent` height or width becomes greater than 0 before triggering the `setCenter` function. The timeout ensures that the observer will eventually disconnect if a resize never happens. I wasn't sure how long to set that for but 5 seconds seemed reasonable.
> fix centerOnInit timing issue

- src/hooks/index.ts
- src/hooks/use-transform-component.tsx
Hook added to return an element, given the current state
Given that v3 introduces the dynamic where `useTransformEffect` is the only hook that has up to date state:
https://github.com/prc5/react-zoom-pan-pinch/blob/c0871e27907c1e9338c613d1e5abfc98a873da52/CHANGELOG.md?plain=1#L5-L7
I wanted to suggest a new style of hook that could return an item, given the internal context.
The reason for this is the following pattern.
Currently if I want to write a component that uses state from inside the context I need to copy that state using `useTransformEffect` to another piece of state to use it like this:
```tsx
const MyComponent: React.FC = () => {
const [scale, setScale] = useState(0);
useTransformEffect(({ state }) => {
const currentScale = state.scale;
setScale(currentScale);
});
return …
```
> feat(transform-hook): UseTransformComponent added

- src/hooks/use-transform-component.tsx
- src/stories/examples/content/content.stories.mdx
- src/stories/examples/zoom-to-element/example.tsx
- src/stories/hooks/use-transform-component.stories.mdx
This fixes `useTransformComponent` to update on change of library context (mimicking `useTransformEffect`.
Also adds docs for hook and a usage in one of the stories.
Follow up to this PR: https://github.com/BetterTyped/react-zoom-pan-pinch/pull/405
> fix: Added docs for useTransformComponent and fixed the hook

- src/components/mini-map/mini-map.tsx
Using viewport to generate a preview, thereby making the minimap display more intuitive.
Also fixed https://github.com/BetterTyped/react-zoom-pan-pinch/issues/471
Old:
New:
> feat: MiniMap preview use viewport ratio

- src/core/instance.core.ts
The Pull Requests addresses the issue: #453 
The problem is that the `onDoubleClick` function is fired twice, once by the correct `dblClick` and the second time by the `touchstart` event.
`onTouchPanningStart` has its own implementation to detect if it was a double tap or not, and if it was, it fired the `onDoubleClick` function. I think the call to `onDoubleClick` is no longer needed and can be removed in favor of the `dbClick` event.
I tested the implementation on the following devices:
- iOS 17.5 Safari 
- iOS 17.5 Chrome
- Android 9 Chrome 126
- MacBook Safari
> fix: only call onDoubleClick for the dblclick event and not for the detected doubleTab in onTouchPanningStart

- src/components/transform-component/transform-component.module.css
This fixed an issue when transforming images in Safari both on desktop and mobile.
This issue was first reported by https://github.com/BetterTyped/react-zoom-pan-pinch/issues/374.
> Fixes blurry images on Safari

- src/core/instance.core.ts
This PR addresses:  https://github.com/BetterTyped/react-zoom-pan-pinch/issues/487
I have output the log of touch events during a pinch on mobile, and it seems to be behaving as follows:
1. The touch event `event.touches.length === 2` is fired only once at the pinch start
2. Two touch events are fired at the pinch start: `event.touches.length === 1` and `event.touches.length === 2`
In case 1, the pinch works correctly. However, in case 2, the quick, consecutive tap events are interpreted as a double-tap.
To address case 2, I have changed it so that only single-finger touches are treated as a double-tap.
> fix: zoom does not work when pinching on mobile

- src/core/handlers/handlers.logic.ts
- src/core/handlers/handlers.utils.ts
This adds the ability to add an offset when zooming to elements. This allows you to zoom to an element and then offset the position so other higher Zindex items don't cover your zoomed element.
> add support for custom offset when zooming to element
